name: Call jenkins job (frontend)
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://3.231.16.151:8080/"
        user: "zenite"
        token: ${{ secrets.TOKEN }}
        job: "deploy"
